/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HooksIndexRouteImport } from './routes/hooks/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ComponentsTitleRouteImport } from './routes/components/title'
import { Route as ComponentsTextRouteImport } from './routes/components/text'
import { Route as ComponentsStackRouteImport } from './routes/components/stack'
import { Route as ComponentsPaperRouteImport } from './routes/components/paper'
import { Route as ComponentsGroupRouteImport } from './routes/components/group'
import { Route as ComponentsCodeRouteImport } from './routes/components/code'
import { Route as ComponentsButtonRouteImport } from './routes/components/button'
import { Route as ComponentsBoxRouteImport } from './routes/components/box'

const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksIndexRoute = HooksIndexRouteImport.update({
  id: '/hooks/',
  path: '/hooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsTitleRoute = ComponentsTitleRouteImport.update({
  id: '/title',
  path: '/title',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsTextRoute = ComponentsTextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsStackRoute = ComponentsStackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsPaperRoute = ComponentsPaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsGroupRoute = ComponentsGroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsCodeRoute = ComponentsCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsButtonRoute = ComponentsButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsBoxRoute = ComponentsBoxRouteImport.update({
  id: '/box',
  path: '/box',
  getParentRoute: () => ComponentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteWithChildren
  '/components/box': typeof ComponentsBoxRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/code': typeof ComponentsCodeRoute
  '/components/group': typeof ComponentsGroupRoute
  '/components/paper': typeof ComponentsPaperRoute
  '/components/stack': typeof ComponentsStackRoute
  '/components/text': typeof ComponentsTextRoute
  '/components/title': typeof ComponentsTitleRoute
  '/components/': typeof ComponentsIndexRoute
  '/hooks/': typeof HooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/box': typeof ComponentsBoxRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/code': typeof ComponentsCodeRoute
  '/components/group': typeof ComponentsGroupRoute
  '/components/paper': typeof ComponentsPaperRoute
  '/components/stack': typeof ComponentsStackRoute
  '/components/text': typeof ComponentsTextRoute
  '/components/title': typeof ComponentsTitleRoute
  '/components': typeof ComponentsIndexRoute
  '/hooks': typeof HooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteWithChildren
  '/components/box': typeof ComponentsBoxRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/code': typeof ComponentsCodeRoute
  '/components/group': typeof ComponentsGroupRoute
  '/components/paper': typeof ComponentsPaperRoute
  '/components/stack': typeof ComponentsStackRoute
  '/components/text': typeof ComponentsTextRoute
  '/components/title': typeof ComponentsTitleRoute
  '/components/': typeof ComponentsIndexRoute
  '/hooks/': typeof HooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/components/box'
    | '/components/button'
    | '/components/code'
    | '/components/group'
    | '/components/paper'
    | '/components/stack'
    | '/components/text'
    | '/components/title'
    | '/components/'
    | '/hooks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/box'
    | '/components/button'
    | '/components/code'
    | '/components/group'
    | '/components/paper'
    | '/components/stack'
    | '/components/text'
    | '/components/title'
    | '/components'
    | '/hooks'
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/components/box'
    | '/components/button'
    | '/components/code'
    | '/components/group'
    | '/components/paper'
    | '/components/stack'
    | '/components/text'
    | '/components/title'
    | '/components/'
    | '/hooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRoute: typeof ComponentsRouteWithChildren
  HooksIndexRoute: typeof HooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/': {
      id: '/hooks/'
      path: '/hooks'
      fullPath: '/hooks/'
      preLoaderRoute: typeof HooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/title': {
      id: '/components/title'
      path: '/title'
      fullPath: '/components/title'
      preLoaderRoute: typeof ComponentsTitleRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/text': {
      id: '/components/text'
      path: '/text'
      fullPath: '/components/text'
      preLoaderRoute: typeof ComponentsTextRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/stack': {
      id: '/components/stack'
      path: '/stack'
      fullPath: '/components/stack'
      preLoaderRoute: typeof ComponentsStackRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/paper': {
      id: '/components/paper'
      path: '/paper'
      fullPath: '/components/paper'
      preLoaderRoute: typeof ComponentsPaperRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/group': {
      id: '/components/group'
      path: '/group'
      fullPath: '/components/group'
      preLoaderRoute: typeof ComponentsGroupRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/code': {
      id: '/components/code'
      path: '/code'
      fullPath: '/components/code'
      preLoaderRoute: typeof ComponentsCodeRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/button': {
      id: '/components/button'
      path: '/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/box': {
      id: '/components/box'
      path: '/box'
      fullPath: '/components/box'
      preLoaderRoute: typeof ComponentsBoxRouteImport
      parentRoute: typeof ComponentsRoute
    }
  }
}

interface ComponentsRouteChildren {
  ComponentsBoxRoute: typeof ComponentsBoxRoute
  ComponentsButtonRoute: typeof ComponentsButtonRoute
  ComponentsCodeRoute: typeof ComponentsCodeRoute
  ComponentsGroupRoute: typeof ComponentsGroupRoute
  ComponentsPaperRoute: typeof ComponentsPaperRoute
  ComponentsStackRoute: typeof ComponentsStackRoute
  ComponentsTextRoute: typeof ComponentsTextRoute
  ComponentsTitleRoute: typeof ComponentsTitleRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

const ComponentsRouteChildren: ComponentsRouteChildren = {
  ComponentsBoxRoute: ComponentsBoxRoute,
  ComponentsButtonRoute: ComponentsButtonRoute,
  ComponentsCodeRoute: ComponentsCodeRoute,
  ComponentsGroupRoute: ComponentsGroupRoute,
  ComponentsPaperRoute: ComponentsPaperRoute,
  ComponentsStackRoute: ComponentsStackRoute,
  ComponentsTextRoute: ComponentsTextRoute,
  ComponentsTitleRoute: ComponentsTitleRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}

const ComponentsRouteWithChildren = ComponentsRoute._addFileChildren(
  ComponentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRoute: ComponentsRouteWithChildren,
  HooksIndexRoute: HooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
